### PR TITLE
Add German (Germany) language

### PR DESCRIPTION
**Pull request by tomatic**
Start of a German translation. Versions for Switzerland should be treated separately, as the Swiss do not use certain characters like ß.

### CODE REVIEW

**Comment by webserviceXXL** [comment]
👍

**Comment by christianblais** [comment]
Awesome. In order to merge this PR, we'll need the language to be added to the list in popup.html.

**Comment by webserviceXXL** [comment]
Maybe it would make sense to localize the language names.

```
<ul>
    <li><a href="#" data-lang>English (Original)</a></li>
    <li><a href="#" data-lang="fr">Français</a></li>
    <li><a href="#" data-lang="de-DE">Deutsch (Deutschland)</a></li>
    <li><a href="#" data-lang="ja">日本語</a></li>
 </ul>
```

**Comment by christianblais** [comment]
Added German translations, and also internationalized the language names.

**Comment by christianblais** [comment]
Thanks a lot for your participation!

**Pull request closed without merging**
